[default]
debug = true
title = "QR Drop"
host = "localhost"
frontend_port = 5173
protocol = "http"
base_frontend_url = "@format {this.PROTOCOL}://{this.HOST}:{this.FRONTEND_PORT}"
base_chat_url = "@format {this.BASE_FRONTEND_URL}/chat"
HEARTBEAT_INTERVAL = 30
HEARTBEAT_TIMEOUT = 10

[default.logging]
version = 1
disable_existing_loggers = false

[default.logging.formatters.default]
format = "%(asctime)s  %(levelname)-8s: %(name)s:%(lineno)d : %(message)s"
datefmt = "%Y-%m-%dT%H:%M:%S"

[default.logging.handlers.console]
class = "logging.StreamHandler"
formatter = "default"
stream = "ext://sys.stdout"

[default.logging.root]
handlers = ["console"]
level = "DEBUG"

[development]
session_storage_folder = "instance/"

[production]
debug = false
session_storage_folder = "/tmp/"

[production.logging.root]
level = "INFO"
