name: Run tests
on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: backend/.python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.8"

      - name: Run tests
        run: uv run pytest

  frontend-test:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      defaults:
        run:
          working-directory: frontend

      steps:
        - uses: actions/checkout@v4

        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version-file: frontend/.node-version
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json

        - name: Install dependencies
          run: npm ci

        - name: Run tests
          run: npx vitest --run
